### ISSUE TITLE
Support for Razer Orochi

### ISSUE THREAD

**Issue by vale2k7** [FruityRazer/FruityUI-Swift#28]
Hey and thanks for this development!
Is it possible to add Razer Orochi Support? On openrazer it's obviously in the list of supported devices (2011 aswell as 2013 and 2015 chroma model)
All the best wishes!

**Comment by edualm** [comment]
Hey,

It should be supported, you can check the device list here: https://github.com/FruityRazer/FruityKit/blob/master/README.md

Are you running into issues?

Thanks for your words! :)

**Comment by vale2k7** [comment]
Thanks for the fast reply! Yes, it should be supported and it also shows my Razer Orochi 2013 being connected. The settings though don't work. 
1. Orochi is only able to be set on or off in case of enlightenment. Though it shows me different options such as breathe or spectrum in a dropdown and in a second dropdown I can choose the direction (actually there's only one LED in the mouse wheel)
2. Got nothing else to set...no button actions, no profiling or anything else. 
![Bildschirmfoto 2021-01-09 um 22 04 03](https://user-images.githubusercontent.com/16323280/104108638-a464be00-52c6-11eb-859d-af037ce452f2.png)

So the only thing working here is the correct detection of the device.
Thanks in advance for any help. :)

**Comment by edualm** [comment]
Hey,

No worries!

I'm afraid in this case the app won't be of much use to you. The only thing supported is the controls of the LEDs - other things like buttons, profiles, etc, are out of scope. This is a simple user space only driver, that only sends messages to the mouse.

Since the mouse only has one led, that you probably can't control, it may not be able to do much. The options that appear are the same for all Synapse 2 devices - theoretically I could filter it by only the available options for each device, but it'd be a manual process. If someone wants to implement that they can, but that's not on my priorities right now I'm afraid.

Sorry to be the bearer of bad news, but that's it, at least for now.
