### ISSUE TITLE
Any plans for button mapping features?

### ISSUE THREAD

**Issue by scrapix** [FruityRazer/FruityUI-Swift#31]
Hey @edualm,
first of all, great work - FruityUi works like a charm and doesn't consume any CPU, while Synapse always makes my MacBook cry with 60-100% CPU consumpation.
Did you ever think about adding button mapping Features for mice? 
In case you do, I could support with UX wireframes if you'd like. Unfortunately I'm not much of a coder :/.

So far I've only found a Linux project which supports mapping https://github.com/z3ntu/razer_test

**Comment by edualm** [comment]
Hello @scrapix,

I am afraid that is out of scope. :(

Button mapping would require writing a system driver that intercepted mouse calls etc., while FruityRazer only aims to be a user-mode app. To be honest, I only wrote it because my Razer Huntsman was stuck in rainbow mode everytime I booted into macOS!

If someone else wants to step up and use FruityUI as a base for button mapping, I'd be more than happy to integrate it into the project, but I don't have the time for that kind of project unfortunately.

Thanks for your words!
